### ISSUE TITLE
Audio fix

### ISSUE THREAD

**Issue by ochompsky** [marcdubois71450/tesla-carplay#11]
The broken audio issues listed: 

- Wireless Carplay
- Siri
- Sound of calls & Microphone
- Steering wheel control 

All 4 of these can be fixed but requires you to run the android version of the autokit app first.  In that app, you change from 'box' mode to 'bluetooth' mode and then the setting will saved to the device.  Alternatively, you may be able to mess around with the files on the dongle itself to make the change but I haven't done it that way.  Once that is done, all of this will work on the Tesla.  

However, the downside is that navigation audio is then broken.  I believe this is a carlinkit issue they are working on but I don't know of a solution.

**Comment by mikegapinski** [comment]
When using the "Bluetooth" mode in Autokit you can pump the navigation audio via web sockets to something like https://github.com/samirkumardas/pcm-player, it'll work when driving. That is something I am doing for the second alpha of Tesla Android

**Comment by marcdubois71450** [comment]
> When using the "Bluetooth" mode in Autokit you can pump the navigation audio via web sockets to something like https://github.com/samirkumardas/pcm-player, it'll work when driving. That is something I am doing for the second alpha of Tesla Android

Thank you for this tip, but the bluetooth solution of the car seems to me a better solution, because the wifi must be reconnected when you switch to driving mode. At least by bluethoot there is no cutoff.




> The broken audio issues listed:
> 
> * Wireless Carplay
> * Siri
> * Sound of calls & Microphone
> * Steering wheel control
> 
> All 4 of these can be fixed but requires you to run the android version of the autokit app first. In that app, you change from 'box' mode to 'bluetooth' mode and then the setting will saved to the device. Alternatively, you may be able to mess around with the files on the dongle itself to make the change but I haven't done it that way. Once that is done, all of this will work on the Tesla.
> 
> However, the downside is that navigation audio is then broken. I believe this is a carlinkit issue they are working on but I don't know of a solution.

I tried this in the latest version v0.3. By directly using the ode-carplay library, made by xxx. It works correctly. I haven't had time to test the microphone, siri and call sound yet. (It's possible that it already works, I don't know if the raspberry (node-microphone) recognizes the tesla bluethoot microphone by default).
And for the steering wheel controls, I have to do a separate piece of code to succeed in recovering the tesla controls with blue-alsa? then send them back to the Carplay.

**Comment by mikegapinski** [comment]
BTW. In my case the Wi-Fi connection doesn't reset when changing gears(see Tesla Android recent YouTube video). 

Make sure that your hotspot boots up quickly before you drive the car. If Wi-Fi connects before switching to drive there is no issue whatsoever. Just select remain connected in drive in your Tesla.

**Comment by marcdubois71450** [comment]
Fix on v0.4
